defaults:
  - base

checkpoint:
  path: models/model.ckpt

preprocessing:
  image_size: [512, 512]

data:
  metadata_csv: ${paths.labels_csv}

thresholds:
  D: 0.35
  G: 0.45
  C: 0.4
  A: 0.4
  H: 0.3
  M: 0.5
  O: 0.35
